### ISSUE TITLE
enable multiple users receipients

### ISSUE THREAD

**Issue by cezio** [GeoNode/geonode-user-messages#5]
User messages have ability to send a message to several users at once:
https://github.com/GeoNode/geonode-user-messages/blob/master/user_messages/views.py#L48

However, this feature is not exposed anywhere, and form with one recipient will always be used. We could use several ways to use form with multiple selection, for example:
 * ``multiple=True`` in query string
 * a setting, ``MESSAGES_ALLOW_MULTIPLE_RECIPIENTS``, which will be used as a value in view kwargs in url pattern: https://github.com/GeoNode/geonode-user-messages/blob/master/user_messages/urls.py#L8
 * additional url, like  ``/message/create/multiple/`` with keyword populated.

**Comment by cezio** [comment]
I think the best way would to have separate url, so deployment can decide which form will be used. In geonode, we can add a setting, then, in views use url for specific version based on that setting. Default behavior will be preserved with easy way to use extended version.

**Comment by afabiani** [comment]
+1

also, let's keep in mind the possibility in the future of filtering the list of target users.
